import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          ink: "#02091A",
          "ink-muted": "#5C5A50",
          ivory: "#F5F1E6",
          muted: "#9A927E",
          gold: "#B68B51",
          "gold-highlight": "#E0C06D",
          "gold-deep": "#8A6A3E",
          canvas: "#FBF8EF",
          surface: "#FFFFFF",
          sunken: "#F1ECDD",
          overlay: "#E7E0CE",
        },
        gold: {
          50: "#F8F3E9",
          100: "#F2EADC",
          200: "#E6D7C0",
          300: "#D7C09E",
          400: "#C8A77A",
          500: "#B68B51",
          600: "#987443",
          700: "#735732",
          800: "#513E22",
        },
        navy: {
          50: "#EDEDEA",
          100: "#DCDEDF",
          200: "#B6BDC8",
          300: "#8795AB",
          400: "#566A8D",
          500: "#1E3A6B",
          600: "#1B3158",
          700: "#182741",
          800: "#141D2D",
        },
        success: {
          50: "#EFF4EA",
          100: "#DEEDDF",
          200: "#BBDCC7",
          300: "#8FC8A9",
          400: "#62B38A",
          500: "#2E9B67",
          600: "#288155",
          700: "#21613F",
          800: "#1B442B",
        },
        danger: {
          50: "#F9EEE6",
          100: "#F5DFD6",
          200: "#ECC0B5",
          300: "#E1998B",
          400: "#D57060",
          500: "#C8422E",
          600: "#A73826",
          700: "#7E2C1D",
          800: "#582014",
        },
        warning: {
          50: "#F8F2E5",
          100: "#F1E8D4",
          200: "#E4D2B0",
          300: "#D4B783",
          400: "#C39A54",
          500: "#B07A1E",
          600: "#936619",
          700: "#6F4D13",
          800: "#4F370E",
        },
        info: {
          50: "#EEF2EF",
          100: "#DEE8E9",
          200: "#BAD2DC",
          300: "#8EB8CC",
          400: "#609CBB",
          500: "#2C7CA8",
          600: "#27678A",
          700: "#204E66",
          800: "#1A3845",
        },
        grey: {
          50: "#F7F8F9",
          100: "#EBEDF0",
          200: "#D3D6DC",
          300: "#B5BAC4",
          400: "#969DAB",
          500: "#777F90",
          600: "#5E6577",
          700: "#474E5E",
          800: "#323845",
          900: "#1E232E",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      fontFamily: {
        sans: ["var(--font-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "1rem",
        "2xl": "1.5rem",
        pill: "2rem",
      },
      boxShadow: {
        soft: "0 2px 8px rgba(2, 9, 26, 0.06)",
      },
      keyframes: {
        "pulse-dot": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.35" },
        },
      },
      animation: {
        "pulse-dot": "pulse-dot 1.6s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
